# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillops < Formula
  desc "Lightweight Go CLI to manage AI agent skills using symlinks"
  homepage "https://github.com/leodinhsa/skillops"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leodinhsa/skillops/releases/download/v0.1.7/skillops_Darwin_x86_64.tar.gz"
      sha256 "db10b95d0d7ebcac91e2df25599e4c7b8c1e20c1e1336e7491c933ea73027b45"

      define_method(:install) do
        bin.install "skillops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leodinhsa/skillops/releases/download/v0.1.7/skillops_Darwin_arm64.tar.gz"
      sha256 "fa68ead21cd1ec77cbc9e501085b8949b576d8f340a902aef88c0d648614ba6f"

      define_method(:install) do
        bin.install "skillops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leodinhsa/skillops/releases/download/v0.1.7/skillops_Linux_x86_64.tar.gz"
      sha256 "94cecd43109d09cf790a0a7bf71ff3e7f37d9de312d05fe6b92d8a2bf08b5037"
      define_method(:install) do
        bin.install "skillops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leodinhsa/skillops/releases/download/v0.1.7/skillops_Linux_arm64.tar.gz"
      sha256 "bb599445b7c79044d13070ce7db37f2258f198d7183d4740c9f59cc1059117fa"
      define_method(:install) do
        bin.install "skillops"
      end
    end
  end

  def caveats
    <<~EOS
      🚀 skillops installed successfully!
      To get started, try running:
        skillops --help
      Or jump right into managing your agentic IDEs:
        skillops agentic
    EOS
  end

  test do
    system "#{bin}/skillops --help"
  end
end
