# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillops < Formula
  desc "Lightweight Go CLI to manage AI agent skills using symlinks"
  homepage "https://github.com/leodinhsa/skillops"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leodinhsa/skillops/releases/download/v1.0.0/skillops_Darwin_x86_64.tar.gz"
      sha256 "7cacf063aa9f58da8f34255c2bd03c6d0172d2091a2a22a7055799b21289e29a"

      define_method(:install) do
        bin.install "skillops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leodinhsa/skillops/releases/download/v1.0.0/skillops_Darwin_arm64.tar.gz"
      sha256 "cd7eb60957727ab72534db630a669cc4975a4ef06a8c59d77572c3a72011869e"

      define_method(:install) do
        bin.install "skillops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leodinhsa/skillops/releases/download/v1.0.0/skillops_Linux_x86_64.tar.gz"
      sha256 "e6fc49787eba82095cc4d45d5241e9cf36dbf729bd513faab91ff8b73bb8856f"
      define_method(:install) do
        bin.install "skillops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leodinhsa/skillops/releases/download/v1.0.0/skillops_Linux_arm64.tar.gz"
      sha256 "3eb625d1f1eed251021553da3f8fe364f1878437d57e801a4548a65448c9d841"
      define_method(:install) do
        bin.install "skillops"
      end
    end
  end

  def caveats
    <<~EOS
      🚀 skillops installed successfully!

      Quick start:
        skillops pull <repo-url>   — download a skill repo
        skillops init              — declare which IDEs this project uses
        skillops add               — link skills into your IDEs
        skillops status            — see what's linked

      Upgrading from v1? Run in each project:
        skillops init
        skillops sync

      Your skill data lives in ~/.skillops/ and is never removed on uninstall.
      To fully clean up: rm -rf ~/.skillops/
    EOS
  end

  test do
    system "#{bin}/skillops --help"
  end
end
