# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillops < Formula
  desc "Lightweight Go CLI to manage AI agent skills using symlinks"
  homepage "https://github.com/leodinhsa/skillops"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leodinhsa/skillops/releases/download/v2.0.1/skillops_Darwin_x86_64.tar.gz"
      sha256 "5debe715d2c24651e29530e075d67bae7f2d3d77c7c6ea8b3b027461b17b03ff"

      define_method(:install) do
        bin.install "skillops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leodinhsa/skillops/releases/download/v2.0.1/skillops_Darwin_arm64.tar.gz"
      sha256 "f24a7d70d3aff6f18e47df2ed35b7c013ebf819321c689a549d050776c4aabf2"

      define_method(:install) do
        bin.install "skillops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leodinhsa/skillops/releases/download/v2.0.1/skillops_Linux_x86_64.tar.gz"
      sha256 "5021afb4d17cf4a0035e8ad6e82794343c38271f5fb8330ad82eb96dfcf694ed"
      define_method(:install) do
        bin.install "skillops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leodinhsa/skillops/releases/download/v2.0.1/skillops_Linux_arm64.tar.gz"
      sha256 "f13267f2f66278c8b3958f00e3e18800001ca02db25d31989bc6f869b1a5d21c"
      define_method(:install) do
        bin.install "skillops"
      end
    end
  end

  def caveats
    <<~EOS
      🚀 skillops installed successfully!

      Quick start:
        skillops pull <repo-url>   — download a skill repo
        skillops init              — declare which IDEs this project uses
        skillops add               — link skills into your IDEs
        skillops status            — see what's linked

      Upgrading from v1? Run in each project:
        skillops init
        skillops sync

      Your skill data lives in ~/.skillops/ and is never removed on uninstall.
      To fully clean up: rm -rf ~/.skillops/
    EOS
  end

  test do
    system "#{bin}/skillops --help"
  end
end
